Filedownload rework
schul-cloud/schulcloud-mobile-ios pull request #148
Opened 2018-10-08 09:17 UTC by Einh06

This PR changes the API for related to file storage. It makes extensive use of ```URLSessionTask```s for better system integration.

2018-10-08 10:08 UTC, mathebox requested changes

2018-10-08 10:08 UTC, mathebox commented on Common/Data/FileSync.swift
> +            guard let files = result.value else {
Here you can use a `switch` statement on the `result` variable.

2018-10-08 10:08 UTC, mathebox commented on Common/Data/FileSync.swift
> +    public func updateContent(of directory: File, completionBlock: @escaping ([File]?, Error?) -> Void) -> URLSessionTask? {
Why no use a signature like this: `@escaping (Result<[File], Error>) -> Void`

2018-10-08 10:08 UTC, mathebox commented on Common/Data/FileSync.swift
> +            }.onSuccess { completionBlock($0, nil) }.onFailure { completionBlock(nil, $0) }
Please multiple lines for this.

Alternatively, see first comment and use `.onComplete { completionBlock($0) }

2018-10-08 10:08 UTC, mathebox commented on Common/Data/FileSync.swift
> +                let json = try JSONSerialization.jsonObject(with: data, options: .allowFragments) as! [String: Any]
Yes, throw an error instead.

2018-10-08 10:08 UTC, mathebox commented on Common/Data/FileSync.swift
> +    private func downloadContent(of directory: File, completionBlock: @escaping ([String: Any]?, Error?) -> Void) -> URLSessionTask? {
I think you can make use of the `Result` type here as well.

2018-10-09 08:21 UTC, mathebox requested changes
There is a shorthand for `Result(error: error)`, it's `.error(error)`. 
The same exists for `Result(value: foo)`: (`.success(foo)`)

2018-10-09 08:21 UTC, mathebox commented on iOS-fileprovider/FileProviderExtension.swift
> +                        switch result {
This switch statement can be simplified to `completionBlock(result.error)`

2018-10-09 08:21 UTC, mathebox commented on Common/Data/FileSync.swift
> +            switch result {
I would prefer something like this:
```swift
let foo = result.map { json in
  return FileHelper.updateDatabase(contentsOf: directory, using: json)
}
completionBlock(foo)
```

Since there are two `Result` object, you can imporve the naming.

2018-10-09 08:21 UTC, mathebox commented on Common/Data/FileSync.swift
>                  return Future(value: files)
Just use `return Future(result: result)`

2018-10-09 08:21 UTC, mathebox commented on iOS-fileprovider/FileProviderExtension.swift
> +                guard let signedURL = result.value else {
Maybe use `.map` here and handle the error at the end of this block

2018-10-09 08:43 UTC, Einh06 commented on iOS-fileprovider/FileProviderExtension.swift
> +                        switch result {
Good catch, much better.

2018-10-09 08:43 UTC, Einh06 commented on Common/Data/FileSync.swift
>                  return Future(value: files)
Will, do much clearer this way.

2018-10-09 08:45 UTC, Einh06 commented on iOS-fileprovider/FileProviderExtension.swift
> +                guard let signedURL = result.value else {
Map won't do the job here because it triggers another tasks, and do not transform the value.

2018-10-09 08:51 UTC, Einh06 commented on Common/Data/FileSync.swift
> +            switch result {
I dont understand what you mean here by 2 `Result` objects. I made some changes here to make the code more concise

2018-10-09 08:55 UTC, mathebox commented on iOS-fileprovider/FileProviderExtension.swift
> +                guard let signedURL = result.value else {
I just noticed this. Shouldn't `DispatchQueue.main.async` be use within the `completionHandler`?

You could also use one of the follwoign apporaches:
- use a switch statement to a avoid force unwrapping the error
- wrap the `self.fileSync.download` call in a future, pass on its result and only have one usage of `completionHandler`

2018-10-09 09:36 UTC, Einh06 commented on iOS-fileprovider/FileProviderExtension.swift
> +                guard let signedURL = result.value else {
This is a system call, i do not have any control on what `completionHandler` is doing. Additionally, there is no benefit in running the `signedURL` completion handler in the main thread.
Wrapping `self.fileSync.download` in `Future` just to reduce the `completionHandler` to one usage seems very much like an overkill. I think it actually obfuscate the simplicity of what's going on. 
I can stand behind the `switch` statement though.

2018-10-09 10:07 UTC, mathebox commented on Common/Data/FileSync.swift
>          request.httpBody = try! JSONSerialization.data(withJSONObject: parameters, options: .prettyPrinted)
use `try?`

2018-10-09 11:34 UTC, mathebox approved these changes

2018-10-09 11:34 UTC, merged