Fixed selection behaviour of HomeworkByDateCell
schul-cloud/schulcloud-mobile-ios pull request #166
Opened 2019-04-05 15:13 UTC by timfraedrich

Fixes [IOS-31](https://ticketsystem.schul-cloud.org/browse/IOS-31?focusedCommentId=26623&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-26623)

### Proposed Changes:

- The course color now remains when the cell is highlighted

2019-04-10 07:09 UTC, mathebox requested changes
Hm... I secretly hoped that there would be a more straightforward way of fixing this. Nevertheless, this looks to me 👍 

Please use spaces of width 4 for the indentation.

Thanks for your contribution! 🎉

2019-04-10 07:09 UTC, mathebox commented on iOS/Views/HomeworkByDateCell.swift
> +    @IBOutlet private var coloredStrip: NonSelectableView!
`UIView` is still fine here since we don't need the specialized type.

2019-04-10 07:09 UTC, mathebox commented on iOS/Views/NonSelectableView.swift
> +			if backgroundColor != nil && backgroundColor!.cgColor.alpha == 0 {
You can simplify this to `self.backgroundColor.cgColor.alpha == 0`

Please use `self` for member attributes.

2019-04-10 07:09 UTC, mathebox commented on iOS/Views/NonSelectableView.swift
> +class NonSelectableView: UIView {
I find this name a bit misleading because there is no code regarding selection.
How about `FixedBackgroundColorView` or somethings similar?

2019-04-10 14:38 UTC, timfraedrich commented
Yes, I hoped as well. I had the same issue with one of my projects and searched hours for a better solution. This was the most elegant thing I could come up with 😅.

> 
> Please use spaces of width 4 for the indentation.
> 
I'm not quite sure if I did that correctly in the last commit, because it added a new parameter in the .pbxproj file and I do not see that for any other file in the project.

All the other things should be fixed.

2019-04-11 03:29 UTC, mathebox approved these changes

2019-04-11 03:47 UTC, mathebox commented
I remove the new parameter manually. Do you global text editing settings differ from mine?

<img width="912" alt="Screen Shot 2019-04-11 at 07 27 50" src="https://user-images.githubusercontent.com/1757680/55929451-d21e5e00-5c2d-11e9-811f-ccd43a6bc4c6.png">

I'm waiting for a green build to merge this PR. Thanks again for this contribution! I think you really saved us some time here 😃

2019-04-11 04:17 UTC, merged